import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faAngleLeft,
  faAngleRight,
  faAnglesLeft,
  faAnglesRight,
  faArrowUpRightFromSquare,
  faArrowsRotate,
  faBars,
  faBolt,
  faCaretRight,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faClock,
  faCopy,
  faEllipsis,
  faHeart,
  faPalette,
  faPlus,
  faSearch,
  faStar,
  faTimes,
  faTrash,
  faTrashAlt
} from '@fortawesome/free-solid-svg-icons';
import { faFacebookSquare, faGulp, faTwitterSquare } from '@fortawesome/free-brands-svg-icons';
import { faStar as farStar, faHeart as farHeart } from '@fortawesome/free-regular-svg-icons';

library.add(
  faSearch,
  faClock,
  faEllipsis,
  faCaretRight,
  faChevronDown,
  faGulp,
  faPalette,
  faTimes,
  faArrowsRotate,
  faCopy,
  faPlus,
  faTrash,
  faTrashAlt,
  faAngleLeft,
  faAngleRight,
  faChevronLeft,
  faChevronRight,
  faAnglesLeft,
  faAnglesRight,
  faArrowUpRightFromSquare,
  faCheck,
  faStar,
  //@ts-ignore
  farStar,
  faBars,
  faFacebookSquare,
  faTwitterSquare,
  faBolt,
  faHeart,
  farHeart
);
